spring.application.name=genaisvc
server.port=8089

# OAuth2 Resource Server - Keycloak JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/finance-manager

#hf.api.url=https://router.huggingface.co/v1/chat/completions
#hf.api.key=${HF_API_KEY}
gemini.api.key=${GEMINI_API_KEY}
gemini.model=models/gemini-2.5-flash
gemini.api.url=https://generativelanguage.googleapis.com/v1beta
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework: DEBUG
logging.level.com.financemanagerai: DEBUG